### ISSUE TITLE
Add leading slash to expectedException

### ISSUE THREAD

**Issue by SoftCreatR** [Idrinth/phpunit-test-generator#46]
Currently:

```
* @expectedException foo\bar\baz\db\FooBarBazException
```

Should become:

```
* @expectedException \foo\bar\baz\db\FooBarBazException
```

**Comment by Idrinth** [comment]
I'm not sure why that is required, phpunit itself uses all expectedException annotations as root-based insteas of based on the current namespace, see https://phpunit.de/manual/6.5/en/writing-tests-for-phpunit.html#writing-tests-for-phpunit.exceptions.examples.ExceptionTest2.php

**Comment by SoftCreatR** [comment]
Ask PHPStorm :)
